// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 38.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'lazy_english';

  static const String assets_images_auth_completed_png = 'assets/images/auth_completed.png';
  static const String lazy_english$assets_images_auth_completed_png = 'packages/lazy_english/assets/images/auth_completed.png';

  static const String assets_images_bow_png = 'assets/images/bow.png';
  static const String lazy_english$assets_images_bow_png = 'packages/lazy_english/assets/images/bow.png';

  static const String assets_images_brain_png = 'assets/images/brain.png';
  static const String lazy_english$assets_images_brain_png = 'packages/lazy_english/assets/images/brain.png';

  static const String assets_images_cheese_png = 'assets/images/cheese.png';
  static const String lazy_english$assets_images_cheese_png = 'packages/lazy_english/assets/images/cheese.png';

  static const String assets_images_compas_png = 'assets/images/compas.png';
  static const String lazy_english$assets_images_compas_png = 'packages/lazy_english/assets/images/compas.png';

  static const String assets_images_crown_png = 'assets/images/crown.png';
  static const String lazy_english$assets_images_crown_png = 'packages/lazy_english/assets/images/crown.png';

  static const String assets_images_dimond_png = 'assets/images/dimond.png';
  static const String lazy_english$assets_images_dimond_png = 'packages/lazy_english/assets/images/dimond.png';

  static const String assets_images_dimond_circular_png = 'assets/images/dimond_circular.png';
  static const String lazy_english$assets_images_dimond_circular_png = 'packages/lazy_english/assets/images/dimond_circular.png';

  static const String assets_images_done_png = 'assets/images/done.png';
  static const String lazy_english$assets_images_done_png = 'packages/lazy_english/assets/images/done.png';

  static const String assets_images_fire_png = 'assets/images/fire.png';
  static const String lazy_english$assets_images_fire_png = 'packages/lazy_english/assets/images/fire.png';

  static const String assets_images_fix_png = 'assets/images/fix.png';
  static const String lazy_english$assets_images_fix_png = 'packages/lazy_english/assets/images/fix.png';

  static const String assets_images_greeting_png = 'assets/images/greeting.png';
  static const String lazy_english$assets_images_greeting_png = 'packages/lazy_english/assets/images/greeting.png';

  static const String assets_images_happy_jumping_png = 'assets/images/happy_jumping.png';
  static const String lazy_english$assets_images_happy_jumping_png = 'packages/lazy_english/assets/images/happy_jumping.png';

  static const String assets_images_lightning_png = 'assets/images/lightning.png';
  static const String lazy_english$assets_images_lightning_png = 'packages/lazy_english/assets/images/lightning.png';

  static const String assets_images_main_image_png = 'assets/images/main_image.png';
  static const String lazy_english$assets_images_main_image_png = 'packages/lazy_english/assets/images/main_image.png';

  static const String assets_images_portfel_png = 'assets/images/portfel.png';
  static const String lazy_english$assets_images_portfel_png = 'packages/lazy_english/assets/images/portfel.png';

  static const String assets_images_speaking_ellingo_png = 'assets/images/speaking_ellingo.png';
  static const String lazy_english$assets_images_speaking_ellingo_png = 'packages/lazy_english/assets/images/speaking_ellingo.png';

  static const String assets_images_star_png = 'assets/images/star.png';
  static const String lazy_english$assets_images_star_png = 'packages/lazy_english/assets/images/star.png';

  static const String assets_images_start_png = 'assets/images/start.png';
  static const String lazy_english$assets_images_start_png = 'packages/lazy_english/assets/images/start.png';

  static const String assets_images_target_png = 'assets/images/target.png';
  static const String lazy_english$assets_images_target_png = 'packages/lazy_english/assets/images/target.png';

  static const String assets_images_think_png = 'assets/images/think.png';
  static const String lazy_english$assets_images_think_png = 'packages/lazy_english/assets/images/think.png';

  static const String assets_images_time_png = 'assets/images/time.png';
  static const String lazy_english$assets_images_time_png = 'packages/lazy_english/assets/images/time.png';

  static const String assets_vectors_add_user_icon_svg = 'assets/vectors/add_user_icon.svg';
  static const String lazy_english$assets_vectors_add_user_icon_svg = 'packages/lazy_english/assets/vectors/add_user_icon.svg';

  static const String assets_vectors_cancel_svg = 'assets/vectors/cancel.svg';
  static const String lazy_english$assets_vectors_cancel_svg = 'packages/lazy_english/assets/vectors/cancel.svg';

  static const String assets_vectors_chat_icon_svg = 'assets/vectors/chat_icon.svg';
  static const String lazy_english$assets_vectors_chat_icon_svg = 'packages/lazy_english/assets/vectors/chat_icon.svg';

  static const String assets_vectors_diamond_svg = 'assets/vectors/diamond.svg';
  static const String lazy_english$assets_vectors_diamond_svg = 'packages/lazy_english/assets/vectors/diamond.svg';

  static const String assets_vectors_elingo_logo_svg = 'assets/vectors/elingo_logo.svg';
  static const String lazy_english$assets_vectors_elingo_logo_svg = 'packages/lazy_english/assets/vectors/elingo_logo.svg';

  static const String assets_vectors_first_place_medal_svg = 'assets/vectors/first_place_medal.svg';
  static const String lazy_english$assets_vectors_first_place_medal_svg = 'packages/lazy_english/assets/vectors/first_place_medal.svg';

  static const String assets_vectors_icon_svg = 'assets/vectors/icon.svg';
  static const String lazy_english$assets_vectors_icon_svg = 'packages/lazy_english/assets/vectors/icon.svg';

  static const String assets_vectors_micraphone_svg = 'assets/vectors/micraphone.svg';
  static const String lazy_english$assets_vectors_micraphone_svg = 'packages/lazy_english/assets/vectors/micraphone.svg';

  static const String assets_vectors_more_icon_svg = 'assets/vectors/more_icon.svg';
  static const String lazy_english$assets_vectors_more_icon_svg = 'packages/lazy_english/assets/vectors/more_icon.svg';

  static const String assets_vectors_search_icon_svg = 'assets/vectors/search_icon.svg';
  static const String lazy_english$assets_vectors_search_icon_svg = 'packages/lazy_english/assets/vectors/search_icon.svg';

  static const String assets_vectors_second_place_medal_svg = 'assets/vectors/second_place_medal.svg';
  static const String lazy_english$assets_vectors_second_place_medal_svg = 'packages/lazy_english/assets/vectors/second_place_medal.svg';

  static const String assets_vectors_send_icon_svg = 'assets/vectors/send_icon.svg';
  static const String lazy_english$assets_vectors_send_icon_svg = 'packages/lazy_english/assets/vectors/send_icon.svg';

  static const String assets_vectors_small_dimond_svg = 'assets/vectors/small_dimond.svg';
  static const String lazy_english$assets_vectors_small_dimond_svg = 'packages/lazy_english/assets/vectors/small_dimond.svg';

  static const String assets_vectors_sound_svg = 'assets/vectors/sound.svg';
  static const String lazy_english$assets_vectors_sound_svg = 'packages/lazy_english/assets/vectors/sound.svg';

  static const String assets_vectors_third_place_medal_svg = 'assets/vectors/third_place_medal.svg';
  static const String lazy_english$assets_vectors_third_place_medal_svg = 'packages/lazy_english/assets/vectors/third_place_medal.svg';

  static const String assets_vectors_volume_svg = 'assets/vectors/volume.svg';
  static const String lazy_english$assets_vectors_volume_svg = 'packages/lazy_english/assets/vectors/volume.svg';
}
